language: node
before_script:
- ls cache;
- touch cache/1.txt
- cat cache/1.txt
- ls -alt
- pwd
- echo 'wow' > cache/1.txt

cache:
   directories:
    - cache
after_script:
- echo 'after'
after_success:
- echo 'done'
